### ISSUE TITLE
Use name of the file as caption-text

### ISSUE THREAD

**Issue by berot3** [alangrainger/obsidian-image-captions#11]
Hi!

Is there a easy way to copy/paste or insert a variable as text? 80% of the time I already wrote as file-name what I want to have as caption.

I thought about something like `![[Big tree.jpg|$]]` so `$` would be a place-holder/variable for the file-name. it picks up the file-name and I dont have to copy paste it :) 

Of course you would have to implement it in you plugin that if $ is the caption than it uses the file-name.

OR - What would be also a intersting way to solve this: add an option to the plugin that if the caption is empty than it will use file-name. if a caption/text is present than not.

What do you think? :)

**Comment by alangrainger** [comment]
Great suggestion! This is added in v1.0.8:

https://github.com/alangrainger/obsidian-image-captions/releases/tag/1.0.8

**Comment by cedrikl** [comment]
Is there a way to also show the file extension in its current implementation? (for example "%%") This is already proving game changer for my workflow as is so thank so yo much for this plugin.

**Comment by alangrainger** [comment]
For my own education, what's the use-case of wanting to show the file extension along with the title?

**Comment by alangrainger** [comment]
@cedrikl from v1.0.9 you can use `%.%` to get filename including extension.

**Comment by cedrikl** [comment]
Thanks Alan! With put the picture name as a caption in our documents because when we export, it moves all those raw pictures to a separate folder. The captions allows the next team to quickly find the original associated to the picture in the document. The file extension is more of a safety in case we have a scenario with PICTURE.jpg and PICTURE.png. It should ensure no two pictures can have the same caption.
