### ISSUE TITLE
Incompatibility with ITS Image Adjustments snippet

### ISSUE THREAD

**Issue by FellowEsin** [alangrainger/obsidian-image-captions#24]
Hello!

I'd like to use this plugin with the [ITS image adjustment snippet](https://github.com/SlRvb/Obsidian--ITS-Theme), but there are some issues. The thing is, when I set the image parameters like this (caption + adjustment), for example
![image](https://github.com/alangrainger/obsidian-image-captions/assets/85190747/f79b597f-cf2d-4a7a-ad08-dfd266bec81b)

It does align the image, and shows the caption, but like this.

![image](https://github.com/alangrainger/obsidian-image-captions/assets/85190747/01ea6e91-68ff-4ee3-8f4f-b4f39cf10d50)

I want to display "Amogus" only, not "Amogus | right".

Any solutions or suggestions?
Thank you.

**Comment by AFellowEsin** [comment]
Addendum: Apparently, [someone has suggested before](https://github.com/alangrainger/obsidian-image-captions/issues/19) that a caption perimeter was added to avoid conflicts with this very snippet. I guess this could be a solution?

**Comment by AFellowEsin** [comment]
Addendum #2: Oddly, the center alignment doesn't work when this plugin is enabled. But when I disable the plugin, it works. So there's this incompatibility as well.

**Comment by alangrainger** [comment]
That's really an issue with that theme. In the [Commonmark spec](https://spec.commonmark.org/0.31.2/#image-description), the image description is the part of markdown between the square brackets on an image link.

```
![Image description](file.jpg)
```

So that theme putting image location commands in that place doesn't seem like a great idea.

However I can see that there is the probability of this theme and other themes/plugins in the future adding all sorts of data into that same image description field.

What I'll do is add a setting where you can add a custom regex to filter the final caption. That should cover all possible use cases into the future, regardless of what plugins or image caption formats people are using.

**Comment by FellowEsin** [comment]
Looking forward for it! Also I'd really like a manual on how to use the custom regex once the feature comes out. Thank you!

**Comment by TDSrock** [comment]
Oh awesome! I completly forgot about this until I got the emails for activity on my original issue. Looming forward to the release!

**Comment by alangrainger** [comment]
@TDSrock @FellowEsin  This has been added in 1.1.2

You can use a custom regex to determine exactly what to parse for the caption, depending on your own preference and vault setup.

In the case of using ITS, the regex should be:

```
^([^|]+)
```

**Comment by FellowEsin** [comment]
YEAAAAH LET'S GOOO! Though how do we use the regex? Can I have an example?

**Comment by alangrainger** [comment]
I literally put the exact example you need in my comment above :grimacing:

**Comment by FellowEsin** [comment]
So it's just surrounding the |? I see. Sorry.

**Comment by alangrainger** [comment]
Just copy and paste exactly this into the settings box, and the caption will ignore anything following a pipe `|` character (which is what ITS uses):

```
^([^|]+)
```

**Comment by FellowEsin** [comment]
Stupid question but, which settings box exactly?

**Comment by alangrainger** [comment]
Did you update the plugin?

**Comment by FellowEsin** [comment]
Yes I have! You were talking about the plugin configs! Sorry.
![resim](https://github.com/user-attachments/assets/bd34ee96-0797-4a68-bee7-bbc52776e6bf)

**Comment by FellowEsin** [comment]
Thank you soooo much!

![resim](https://github.com/user-attachments/assets/a280faa7-c4f0-4027-a5a3-99790a61a428)
![resim](https://github.com/user-attachments/assets/4d8c349c-4c53-407b-b345-de47a0375abf)

**Comment by alangrainger** [comment]
No problem, glad it's all working! :)

**Comment by FellowEsin** [comment]
Sorry to say this, but there is some sort of new problem: It causes problems with links.

![resim](https://github.com/user-attachments/assets/aad2db60-5fe0-4254-8b2c-3c683b568e49)
![resim](https://github.com/user-attachments/assets/83228b7a-a688-4f27-a42c-8dde86c2b420)

And when you want to actually use | in your caption, it's another problem.
![resim](https://github.com/user-attachments/assets/feb7d0e1-cef3-47f2-a202-dfad2f26d879)
![resim](https://github.com/user-attachments/assets/d2481964-67bb-4593-98ce-6f3b8df2e256)

Is there a workaround to this or anything?

**Comment by alangrainger** [comment]
Firstly, that would never work. You can't specify a link like that as the first set of `]]` would close the outer link.

You need to follow [the documentation](https://github.com/alangrainger/obsidian-image-captions?tab=readme-ov-file#markdown-in-captions) and use `<<` `>>` for wikilinks:

> To use Wikilinks, you'll need to swap your square brackets [[]] for angle brackets <<>>:
> 
> `![[image.jpg|This is a caption with <<a Wikilink>>]]`

Secondly, the reason for using the regex is so that you can customise it for your exact use case, since I couldn't possibly cover all plugins/themes/usecases myself.

Just change the regex to allow an escaped pipe:

```
^(\\\||[^|])+
```

For any other cases you come across, please research on Google how to write the correct regex expression. You don't need to post any other comments here - you can customise the regex yourself to handle any custom cases in your own unique vault setup.

**Comment by FellowEsin** [comment]
So cool! Thank you so much!

**Comment by alangrainger** [comment]
@FellowEsin  Please update to 1.1.3 - I had forgotten to include the theme's CSS file in the 1.1.2 release :grimacing:

**Comment by FellowEsin** [comment]
What do you mean by the theme's CSS file?

**Comment by alangrainger** [comment]
This file. Just update to 1.1.3 and it will be fixed.

![image](https://github.com/user-attachments/assets/283b1107-a23f-4ee5-9534-c4a725d66f1c)

**Comment by FellowEsin** [comment]
Ohhh okay! Updated! Thanks a lot!

**Comment by FellowEsin** [comment]
Hey, I'm wondering, how can I align the image and not set a caption?
