### ISSUE TITLE
Editing text directly adjacent to an image w. caption causes the caption to render repeatedly on each edit

### ISSUE THREAD

**Issue by luckman212** [alangrainger/obsidian-image-captions#5]
@alangrainger neat plugin! (thank you) 👏 

A picture (well, video) is worth 1000 words here. This was captured using Obsidian 1.1.12 (installer 1.1.9) in a fresh Sandbox vault, with only this plugin enabled.

(The interesting part begins at 00:18)

https://user-images.githubusercontent.com/1992842/218337356-a370a2a8-e8ab-4510-bad1-445b80dedcf4.mp4

**Comment by alangrainger** [comment]
Excellent bug report, thank you!

I can replicate it, but it might take some work to resolve this particular case. The method to add captions is highly fragile as there doesn't seem to be any reliable way to hook into Obsidian's image rendering.

For now, the workaround is to leave a gap - don't type directly next to an image. If you want to spend some time trying to find a fix, please submit a Pull Request it would be greatly appreciated.

**Comment by alangrainger** [comment]
Excellent bug report, thank you! This should hopefully be resolved in 1.0.7. Please have a test and let me know. 

The method to add captions is highly fragile as there doesn't seem to be any reliable way to hook into Obsidian's image rendering, so there are bound to be other niche cases not fixed by this release.

**Comment by luckman212** [comment]
Wow, awesome. Thank you! :rocket:
